### ISSUE TITLE
Tandem Docs don't Run vis HTTPS in Lando

### ISSUE THREAD

**Issue by dustinleblanc** [thinktandem/tandem#15]
1. Describe the issue in a few sentences. Try to be as succinct and high level as possible. The goal is to be able to quickly communicate, you could think about it as just writing a slightly more detailed version of the title. You'll be able to be more detailed later.

The docs sites does not properly render with HTTPS locally when run via Lando. You get a blank white page

2. Write out concrete steps someone can take to replicate the bug or problem.

Run `lando start`. After Lando boots up, click the HTTPS url because even though it doesn't matter locally, you're that kind of SECUREALLTHETIME dev, and you want the damn green lock. After a minute you realize no more page is coming and this blank milky whiteness is all you are destined for and you question your existence.

3. Sketch a proposed solution. If this is an improvement a user story might be a good place to start. This does not have to be a techincal suggestion although it certainly can be if that makes sense.

This is likely fixable by somehow telling Node itself to load SSL keys that are generated by Lando

4. Make sure you complete the following checklist

- [x] I've added either the `bug` or `improvement` label
- [x] I've selected the label that _best_ describes what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**

**Comment by pirog** [comment]
@dustinleblanc for the sake of standardization im going to close this out and suggest you RESUBMIT as either a chain of tasks (if you've got a clear picture on what needs to happen) or as a "discussion" if you've like to get some more feedback. 

FWIW i think the underlying issue here is actually vuepress
https://github.com/vuejs/vuepress/issues/72

Here is what shows up in my console on chrome and a "workaround" to approve "unsafe" scripts
![Screen Shot 2019-06-30 at 8 17 16 PM](https://user-images.githubusercontent.com/713424/60404171-2cb3c000-9b74-11e9-9c1c-0f3d97e32b20.png)
![Screen Shot 2019-06-30 at 8 17 16 PM](https://user-images.githubusercontent.com/713424/60404173-33423780-9b74-11e9-9305-9bd544a36282.png)

**Comment by pirog** [comment]
fake out!

backtracking here. after looking at a few of the other issues i think it makes more sense from a tracking perspective to keep this open and classify it as a "note"
