### ISSUE TITLE
What are Service Products?

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#40]
## Prompt

One of Tandem's core goals is to create reproducible packages of services for clients. What starts as a one-off service becomes a process codified with documentation that can be delivered as a "service product" for reliable price points and producing a reliable margin. Automation and further marketing may allow a service product to actually become a SaaS offering in the future.

The goal of this discussion is to agree upon a definition for service products and brainstorm a few ideas. Some targets we've discussed in the past include...

- SEO audits
- Performance audits
- Drupal minor-version upgrades
- D6/7 LTS migrations
- Ektron migrations

## Ticket Checklist

Make sure you complete the following checklist

- [x] I'm aware of [what a discussion actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc

**Comment by pirog** [comment]
My definition of service product would roughly be something like

> Any repeatable process that can be used on a wide variety of projects, done in a predictable-ish time horizon and produce consistent, standardized deliverables

Ideally these would be mostly automated processes. I think it might be worth differentiating service products into two separate "classes", 

## 1. SaaSy SPs - ones that could ultimately be crafted into some sort of SaaS offering which to me means they are 100% (or very close to) automated and produce an actual standardized deliverable eg a report. High level these things are functional eg INPUT X -> OUTPUT Y. An example of this would be something like a performance or code quality audit.

## 2. Internal SPs - these are things that we might be able to line item on a client SoW at a fixed price because we know we can do them consistently within a reasonable RANGE of price, eg they are MOSTLY automated. An example of this would be something like an "onboarding and project scaffolding" line item that forks a start state, sets up lando, testing, platform.sh, populates labels and common tickets, etc.

**Comment by pirog** [comment]
As far as ideas go, i think the following are things that might be both the most accessible (eg things we've already started to "productize") and immediately useful to us

1. Some sort of "project onboarding and scaffolding" line item
2. SEO audit
3. Performance audit
4. Code review (ideally for use in some wider pre-project-start techincal audit/discovery but could also be something we use periodically to report on the quality/improvement we are making to a codebase)
5. D8 Migrations 
6. Security audit
7.

**Comment by pirog** [comment]
@labboy0276 your feedback is required over here so we can start to advance this shit

**Comment by labboy0276** [comment]
@pirog @reynoldsalec Here are my thoughts with this item:

I agree with a good chunk of what @pirog says with some exceptions.  Things like D8 Migrations are just too broad and could never be encompassed with a flat price.  I also think it is a service we should sell to agencies in general.  Just use the line of we have a migration guru, need help to dealio.  Obviously it would be more fleshed out than that.  Anywho.....

I also think our service products would be almost a gateway for leads to come in as support clients.  The easiest and fastest way to do this I have seen over the years are SEO Audits, Code / Bug Review Audits & Performance Audits.  A newer service we had some traction on with a couple blasts were D6 LTS Implementation & legacy D7 updates.  All of these products can be done quickly (for the most part) on our end and we could make a nice profit on each one.  They are easier to sell and there is enough API automation to identify potential leads with these as well.

**Comment by reynoldsalec** [comment]
Some notes from our conversation:

- Discovery would be a combination of different service products.
- Dustin mentioned Thoughtbot's approach to productize [discovery](https://thoughtbot.com/services)

**Comment by reynoldsalec** [comment]
Need to make a documentation followup!

**Comment by pirog** [comment]
alright ive got a task to document this
https://github.com/thinktandem/tandem/issues/116

@reynoldsalec id check that out, particularly the next tasks part. i dont want the energy for this to die once the documentation task is done, maybe #41 makes sense?
