### ISSUE TITLE
Port Over Old Sales Docs

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#45]
## What is to be done?

- Move over the Sales Principles (Ultimate Goals) and Channels from (this Doc)[https://docs.google.com/document/d/1QhVpnroyDmVFqM5bhqDkTDdLFOlFVIdPFWznwhKurj4/edit#]
- Move over Audiences/Personas from this Doc and other Drive Documentation.
- Define the ideal steps in our current sales funnel.

## Task checklist

- [x] I'm aware of [what a task actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc
- [x] I've added a story point estimation. **This should never exceed 3!!!**
- [x] I've created a follow up task or discussion and linked to it in the section below or labeled this as a "one-off" task if there is no follow up task

**Comment by pirog** [comment]
@reynoldsalec @labboy0276 it might be worth looking at the old docs for other things you can move over

To that end @serundeputy has given some feedback on them
https://github.com/thinktandem/tandem/issues/35#issuecomment-509653041
note that his feedback includes other non-related-to-sales stuff

**Comment by labboy0276** [comment]
OK @pirog @reynoldsalec I got a few things done here.

I ported over https://docs.v1.thinktandem.io/marketing/marketing-channels.html and voltroned it with our channels in the Manifesto.  Renamed it Sales & Marketing Channels.

I ported over https://docs.v1.thinktandem.io/sales/sales-script.html pretty much as is and tweaked a thing or two.  Once we flesh out https://github.com/thinktandem/tandem/issues/67 more, we can come back and tweak this.

I **did not** port over https://docs.v1.thinktandem.io/sales/customer-profiles.html as I see no purpose in this currently.  We kind of are fleshing this out more in our personas section.

I **did not** port over https://docs.v1.thinktandem.io/sales/rfp-process.html as this needs to be rethought due to our experience with RFPs prior, maybe spin out another task to chat more about redoing this section?

I still need to do "Define the ideal steps in our current sales funnel."

PR: https://github.com/thinktandem/tandem/pull/70
